--drop table if exists whatsup_task;
--drop table if exists whatsup_user;
--
--create table whatsup_task (
--	id bigint generated by default as identity,
--	title varchar(128) not null,
--	description varchar(255),
--	user_id bigint not null,
--    primary key (id)
--);
--
--create table whatsup_user (
--	id bigint generated by default as identity,
--	login_name varchar(64) not null unique,
--	name varchar(64) not null,
--	password varchar(255) not null,
--	salt varchar(64) not null,
--	roles varchar(255) not null,
--	register_date timestamp not null,
--	primary key (id)
--);

drop table if exists whatsup_app_item;
drop table if exists whatsup_app_user;
drop table if exists whatsup_app_image;

create table whatsup_app_item (
	id bigint generated by default as identity,
	name varchar(128) not null,
	description varchar(255) not null,
	item_type varchar(50) not null,
	publish_date timestamp not null,
	user_id bigint not null,
    primary key (id)
);

create table whatsup_app_user (
	id bigint generated by default as identity,
--	login_name varchar(64) not null unique,
	name varchar(128) not null,
	email varchar(255),
	password varchar(255),
	register_date timestamp not null,
	last_sync_date timestamp not null,
	last_sync_location varchar(128),
	primary key (id)
);

create table whatsup_app_image (
	id bigint generated by default as identity,
	name varchar(128) not null,
	path varchar(255) not null,
	creation_date timestamp not null,
	item_id bigint not null,
	primary key (id)
);
